### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by sedflix** [SpoonLabs/coming#100]
I was trying to run the module on commons-lang(5468 commits) and I got the following error:

```
Analyzing 1022/5468
2019-07-05 11:41:06,797 INFO fr.inria.coming.changeminer.analyzer.commitAnalyzer.FineGrainDifftAnalyzer -
*****
Commit: 5111ae7db08a70323a51a21df0bbaf46f21e072e
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
.... 
<this stack trace can be different>
```

**Comment by martinezmatias** [comment]
Hi @sedflix 
Good point. After analyzing a commit, Coming stores, by default, the results obtained from the analyzers from that commit. So, it there are many commit, we can obtain the problem you describe. However, We can disable to store the results. For that, we should put the property `save_result_revision_analysis` in `False`
WDYT?
Regards
Matias

**Comment by sedflix** [comment]
Should we add a FAQ section to README.md answering these kinds of questions?

**Comment by sedflix** [comment]
Hi @martinezmatias ,

In this case we don't get the output from our analysis, right?

**Comment by martinezmatias** [comment]
Hi @sedflix 

> Should we add a FAQ section to README.md answering these kinds of questions?

Yes, it's a very good idea. That part should be clarified!

**Comment by martinezmatias** [comment]
Hi @sedflix 

> In this case we don't get the output from our analysis, right?

Exact. Also a point to clarify in the doc.
(If you want to see that in the code is here:   https://github.com/SpoonLabs/coming/blob/master/src/main/java/fr/inria/coming/core/engine/RevisionNavigationExperiment.java#L79).

One thing that we can add in the doc is that argument `save_result_revision_analysis`  can be used together with the Result Callback mechanism: see test here: https://github.com/SpoonLabs/coming/blob/214ed3dc016074cda2afede820a6586ee23f45a4/src/test/java/fr/inria/coming/spoon/core/MainComingTest.java#L170
