### ISSUE TITLE
gumtree does not provide an output

### ISSUE THREAD

**Issue by niloofartrg** [SpoonLabs/coming#102]
I have written this test case for NPEfix and I can't figure out why gumtree does not find any difference between these two files? @martinezmatias 

`

    public static void main (String[] args) {

        hello();

        void hello(){
            String ptr = null;

            if (ptr.equals("gfg"))
                System.out.print("Same");
            else
                System.out.print("Not Same");
        }

    }

`

`

    public static void main (String[] args) {

        hello();

        void hello(){
            String ptr = null;

            return ;
            if (ptr.equals("gfg"))
                System.out.print("Same");
            else
                System.out.print("Not Same");
        }

    }

`

**Comment by monperrus** [comment]
Thanks for noticing this problem. Could you open a pull-request with a failig test case on https://github.com/SpoonLabs/gumtree-spoon-ast-diff/?

**Comment by niloofartrg** [comment]
I did that. Thanks.
