### ISSUE TITLE
identify commits that are in the search space of program repair systems

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/coming#109]
* [ ] ACS
* [x] Arja
* [ ] CapGen
* [x] Elixir
* [ ] HDRepair
* [x] JGenProg
* [x] JKali
* [x] JMutRepair
* [ ] Jaid
* [x] Nopol
* [x] NpeFix
* [ ] Sequencer
* [ ] SimFix
* [ ] SketchFix
* [ ] ssfix

**Comment by sedflix** [comment]
Nopol seems to be repeated twice.

**Comment by martinezmatias** [comment]
Hello @sedflix @niloofartrg 
Can we check NpeFix and jGenProg?

**Comment by monperrus** [comment]
Added Sequencer to the list see http://arxiv.org/pdf/1901.01808

**Comment by monperrus** [comment]
See [Estimating the Potential of Program Repair Search Spaces with Commit Analysis](http://arxiv.org/pdf/2007.06986) (Khashayar Etemadi, Niloofar Tarighat, Siddharth Yadav, Matias Martinez and Martin Monperrus), In Journal of Systems and Software, 2022
