### ISSUE TITLE
add support for python?

### ISSUE THREAD

**Issue by Amirhgh74** [SpoonLabs/coming#145]
Hello @martinezmatias  and thank you for your great library.
I am doing research on python language and I want to know if you added python support for coming.
I didn't see the language support in the README. 
I would also be glad if I can contribute in adding Python support. 

let me know if I can have your email address to contact you about this issue :)

**Comment by martinezmatias** [comment]
Dear @Amirhgh74 
cc @monperrus 

> I am doing research on python language and I want to know if you added python support for coming.

We current version of Coming analyzes Java code.

> I would also be glad if I can contribute in adding Python support.

It will be nice! Contributions are welcome.

Our emails are in the readme.  We can also continue discussing via GH issues.
