### ISSUE TITLE
GenProg  and Arja pattern files

### ISSUE THREAD

**Issue by niloofartrg** [SpoonLabs/coming#149]
Hello, @martinezmatias @monperrus 
I have been reading the Arja paper, but something that is not clear for me is that it seems the pattern files of Genprog and Arja would be the same. Am I right about this? Thanks!

**Comment by martinezmatias** [comment]
Hi @niloofartrg 

> I have been reading the Arja paper, but something that is not clear for me is that it seems the pattern files of Genprog and Arja would be the same. Am I right about this? 

If I am not wrong, one of the modes of Arja is based on  GenProg. 
The main difference between it and GenProg (original) is the fitness function. That is, the *way*  that a repair approach evaluates (and decides) if a candidate patch is a solution or not. 
However, I am not sure if the approach of Arja and even the implementation follows 100% the general idea of GenProg.

**Comment by niloofartrg** [comment]
Thanks for the explanation.
I was basing my thought based on the below paragraph from the Arja paper. If they are considering the same operations the patterns would be the same?

 Similar to GenProg [9], ARJA uses three kinds
of operations: delete, replace, and insert. More specifically, for
each likely-buggy statement, ARJA either deletes it, replaces
it with one of its ingredient statements, or inserts one of its
ingredient statements before it

**Comment by martinezmatias** [comment]
> If they are considering the same operations the patterns would be the same?

Yes. However, take in account that the implementation jGenProg adds a new operator: Insert *After* (I am not sure if the Arja's implementation also considers it).
Moreover, I dont know how is the strategy that Arja does for picking statements to be used in the Replace and Insert operators. in JGenProg we have tree modes: 1) to take statements from the buggy file, 2) from the package containing the buggy file, 3) from any place. (By default, jGenProg works in the mode package (i.e., the second item))

**Comment by niloofartrg** [comment]
thanks for the explanation! @martinezmatias
