### ISSUE TITLE
compute the false positive and false negatives over drr

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/coming#152]
Hi @niloofartrg could you compute the current number of false positives and false negatives over @sophiehye's drr?

**Comment by niloofartrg** [comment]
Hello,
 on NPEfix patches in drr repo :  

Arja: 5/11 FP
NPEfix: 2/11 FP
JKali: 0/11 FP
NoPol:1/11 FP
genprog: 5/11 FP
Elixir: 2/11 FP
NO FN's were found.


on Elixir patches in drr repo:
genprog : 1/3 FP
NpEfix : 1/3 FP
others didn't have FP.
No FN was detected.

@monperrus 
I'll work on solving these cases.

**Comment by monperrus** [comment]
cool results. We need to clarify how you compute FP. Where is the code doing so?

**Comment by niloofartrg** [comment]
I did it manually by looking at the changes in the file.
there is no label indicating all possible repair tools so how can I do that with a code do?

**Comment by monperrus** [comment]
the goal is to make it automatically, this can be automated as follows:

```
for all patches p in DRR:  
	 detectors = set of all repair tools that match p
     if p_{tool} in detectors: true_positive++
     if p_{tool} not in detectors: false_negative++
```

**Comment by niloofartrg** [comment]
aha!! I'll do this. I thought there should be something completely automatic! this still needs to compute detectors manually

**Comment by monperrus** [comment]
yes, it is 100% automatic. the detectors are those you've implemented.

**Comment by niloofartrg** [comment]
If I understand correctly, for each pair of files P, detectors are the set of repair tools that could have generated each P, so they should be computed manually and specific to each P, am I wrong?

**Comment by monperrus** [comment]
Done is [Estimating the Potential of Program Repair Search Spaces with Commit Analysis](http://arxiv.org/pdf/2007.06986)
