### ISSUE TITLE
NPEfix patch

### ISSUE THREAD

**Issue by niloofartrg** [SpoonLabs/coming#158]
These two snippets are from the NPEfix patch but I don't think that they could be generated by NPEfix repair tool regarding NPEfix's method. Am I right? @monperrus 

<img width="1191" alt="Screen Shot 2019-09-04 at 15 59 23" src="https://user-images.githubusercontent.com/24320932/64261700-34edfa00-cf2d-11e9-8ede-01320cf11b96.png">

<img width="1231" alt="Screen Shot 2019-09-04 at 15 59 05" src="https://user-images.githubusercontent.com/24320932/64261722-3e776200-cf2d-11e9-8336-8f91ed67756a.png">

**Comment by monperrus** [comment]
https://user-images.githubusercontent.com/24320932/64261700-34edfa00-cf2d-11e9-8ede-01320cf11b96.png
cannot be a NpeFix patch, that seems to be a bug in DRR @sophiehye WDYT?
