### ISSUE TITLE
FileNotFound in repairability mode for windows users

### ISSUE THREAD

**Issue by khaes-kth** [SpoonLabs/coming#170]
When I execute the tool in repairability mode, I face FileNotFound exception. The reason seems to be in line 74 of AbstractRepairTool.java where it is assumed that "/tmp/" path exists on the system while windows users might not have that path on their systems. @monperrus

**Comment by martinezmatias** [comment]
Hi @khaes-kth 
Thanks for reporting the problem.
The /tmp is harcoded here: https://github.com/SpoonLabs/coming/blob/HEAD/src/main/java/fr/inria/coming/repairability/repairtools/AbstractRepairTool.java#L74 
We should use File.createTempFile when we create temporal files

**Comment by monperrus** [comment]
Thanks for the detailed report. I guess that's an easy fix for your very first pull request!
