### ISSUE TITLE
Repairability mode prints PatternInstanceAnalyzer results instead of RepairabilityAnalyzer results

### ISSUE THREAD

**Issue by khaes-kth** [SpoonLabs/coming#172]
In https://github.com/SpoonLabs/coming/blob/master/src/main/java/fr/inria/coming/repairability/JSONRepairabilityOutput.java#L31 the results of PatternInstanceAnalyzer are used to generate the output (instead of RepairabilityAnalyzer results). Is it how the tool is supposed to work? The problem is that some of the results are filtered by RepairabilityAnalyzer (ex, commits that change more than one java file) but currently this filtering does not affect the output. @martinezmatias @monperrus

**Comment by martinezmatias** [comment]
HI @khaes-kth 

Thanks for the issue.
You are right. The JSON output from RepairabilityAnalyzer  does contains not info about the repairability. Actually it outputs the instances found by the PatternInstanceAnalyzer module. 

I list the points to be fixed IMO:

- [ ] I would create a new entity that represents the results of the ReparabilityAnalyzer.  Right now that analyzer returns  as result  ([here](https://github.com/SpoonLabs/coming/blob/HEAD/src/main/java/fr/inria/coming/repairability/RepairabilityAnalyzer.java#L80) ) an object of type `PatternInstancesFromRevision` , which is the entity used another module (PatternInstanceAnalyzer). This new result entity that represents the  repairability result would be quite similar to the PatternInstancesFromRevision. However, we would add additional information that right now is missing,  for example, the tool that is able to synthesize the commit, the "template" used for synthesizing it, etc.

- [ ]  Add a test for each  type of JSON generated (not only related to the RepairabilityAnalyzer)

**Comment by khaes-kth** [comment]
Hi @martinezmatias ,
Thank you for your consideration.

One tiny note: the information regarding the used tool and template can be (and is already) retrieved from PatternInstancesFromRevision (from the name of the used pattern); however, it would be surely better if they were mentioned explicitly.

**Comment by martinezmatias** [comment]
@khaes-kth 

> One tiny note: the information regarding the used tool and template can be (and is already) retrieved from PatternInstancesFromRevision

Thanks for the clarification. That's true: the names are on the pattern specification.

> however, it would be surely better if they were mentioned explicitly.

Yes, actually we new result entity returned by the `RepairabilityAnalyzer` could extend the `PatternInstancesFromRevision`

**Comment by sedflix** [comment]
> The problem is that some of the results are filtered by RepairabilityAnalyzer (ex, commits that change more than one java file) but currently this filtering does not affect the output.

IMO, it would nice to have one test case about "commits that change more than one java file".

**Comment by martinezmatias** [comment]
Hi @sedflix 

> IMO, it would nice to have one test case about "commits that change more than one java file".

Yes, that's a functionality that we need to finish and test from the `PatternInstancesAnalyzer`. I have stated implementing them but I did not arrive to change specification.

**Comment by martinezmatias** [comment]
Hi @khaes-kth 

This issue has been merged. Is it Ok to close the issue?

**Comment by khaes-kth** [comment]
Hi @martinezmatias ,

Yes, it is done. I will close it.
