### ISSUE TITLE
Testing of Features

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/coming#185]
All tests of features were commented (I imagine after refactor and merging with the folk).

I uncommented and repaired one of them (https://github.com/SpoonLabs/coming/blob/3c063f491172f6082b57f4ca364f3575728ced38/src/test/java/fr/inria/coming/spoon/features/CodeFeatureDetectorTest.java#L142) but we must be uncomment all of them.

**Comment by monperrus** [comment]
@sophiehye WDYT?
