### ISSUE TITLE
Need more information in README 

### ISSUE THREAD

**Issue by rem2016** [SpoonLabs/coming#21]
Thanks! Coming is very helpful for my research. Do you mind adding a few more descriptions about this tool?

- Supported languages
- Which branch it mines in default

**Comment by martinezmatias** [comment]
Dear @rem2016 
We are glad that Coming is useful for your research.
We plan to update the README very soon. (I have just updated the readme with a small clarification about the branch)

> Supported languages

For the  moment only Java, but we are working to accept other languages

> Which branch it mines in default

By default it mines `master` branch, but I can be changed using the command line argument `-branch`

Cheers
Matias
