### ISSUE TITLE
add the ADD features in coming

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/coming#228]
add the ADD features in coming by adding ADD (https://github.com/lascam-UFU/automatic-diff-dissection/) as dependency

have all repair patterns as Coming features

see https://github.com/lascam-UFU/automatic-diff-dissection/blob/master/src/main/java/add/entities/RepairPatterns.java

**Comment by monperrus** [comment]
@tdurieux will release a snapshot of ADD in his own Maven repo.

**Comment by tdurieux** [comment]
ADD is deployed to https://github.com/tdurieux/maven-repository

**Comment by tdurieux** [comment]
see #229

**Comment by monperrus** [comment]
closed by #229
