### ISSUE TITLE
Code features not used

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/coming#235]
I am not sure if we use the features [S4R](https://github.com/SpoonLabs/coming/tree/master/src/main/java/fr/inria/prophet4j/feature/S4R) and [S4R0](https://github.com/SpoonLabs/coming/tree/master/src/main/java/fr/inria/prophet4j/feature/S4RO) 
Should we remove them?

@SophieHYe  WDYT?

**Comment by SophieHYe** [comment]
Hi Matias,  

I would prefer to remove the features of S4R0 for a more clear structure of coming code features.

**Comment by monperrus** [comment]
S4R0 removed in #257
