### ISSUE TITLE
Usage of features

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/coming#242]
Hi @SophieHYe 

It seems that the entity that prepares the features for Repairnator [RepairnatorFeatures](https://github.com/SpoonLabs/coming/blob/63f470665df627b6ebcba90f809dd1a3e0cda4af/src/main/java/fr/inria/coming/codefeatures/RepairnatorFeatures.java) does not consider the `Contextual Syntactic features` (i.e., the also named S4R features ).
Here, the code calls to the P4J and later to the ADD.
https://github.com/SpoonLabs/coming/blob/63f470665df627b6ebcba90f809dd1a3e0cda4af/src/main/java/fr/inria/coming/codefeatures/RepairnatorFeatures.java#L151

This way of extracting the features is different than that one uses in the paper, which uses the [FeatureAnalyzer.](https://github.com/SpoonLabs/coming/blob/4b80d6b16c4b3bb35827e5ae9304431c306247e6/src/main/java/fr/inria/coming/codefeatures/FeatureAnalyzer.java)

Am I missing something?
Thanks!

**Comment by monperrus** [comment]
FYI, removed outdated `RepairnatorFeatures` in #262.
