### ISSUE TITLE
Filtering ODS features

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/coming#243]
We should include an option to only export the features we use in the ODS' paper. 
That would help to reproduce the experiment.

@SophieHYe  WDYT?

**Comment by monperrus** [comment]
Yes, for reproducibility, we need to have a flag with the exact set of features as used in the paper http://arxiv.org/pdf/1910.12057.

**Comment by monperrus** [comment]
Having spent a bit of time in the code, I believe the paper features are that of `ExtendedFeatureExtractor`
