### ISSUE TITLE
[Question] Extending the 'findPatternInstance' function

### ISSUE THREAD

**Issue by NunoCastanho** [SpoonLabs/coming#244]
Hello.

I'm curious to know your opinion and thoughts on how easy or how difficult it would be to extend the function `findPatternInstance` in the `DetectorChangePatternInstanceEngine` class to work with merge situations? More precisely, receive another `Diff` object as well as some information regarding the base version of the two variants.

Thanks,
Nuno

**Comment by martinezmatias** [comment]
Hi @NunoCastanho 

It can be possible to overload the method `findPatternInstance` to receive a second DIFF.  The challenge would be to change the navigation engine (`RevisionNavigationExperiment`) to detect the merge and thus to compute  the two diff.
Then, the complexity will depend on the task you want to apply into the `findPatternInstance `which receives the two diffs.

Regards
Matias
