### ISSUE TITLE
thesis: Leveraging Coming for designing diff contracts to automatically check pull requests

### ISSUE THREAD

**Issue by khaes-kth** [SpoonLabs/coming#250]
There are pull requests that follow certain patterns. For example, https://github.com/INRIA/spoon/pull/4534, https://github.com/INRIA/spoon/pull/4533, https://github.com/INRIA/spoon/pull/4532, and https://github.com/INRIA/spoon/pull/4531 migrate different test classes to JUnit 5 using very similar change patterns.

An idea is to develop a GHAction that allows developers design diff contracts in the form Coming specifications. This GHAction should be triggered whenever there is PR with a specific label/tag/keyword and comment on the PR if the changes of the PR correspond to a specified diff contract.

**Comment by khaes-kth** [comment]
@monperrus : Do we also add our ideas in this project or should I move this to the Spoon repo?

ping @algomaster99

**Comment by martinezmatias** [comment]
Hi @khaes-kth 

> An idea is to develop a GHAction that allows developers design diff contracts in the form Coming specifications. This GHAction should be triggered whenever there is PR with a specific label/tag/keyword and comment on the PR if the changes of the PR correspond to a specified diff contract.

It's a great idea. 

> GHAction should be triggered whenever there is PR with a specific label/tag/keyword

Could be also implemented as a GH Check?

**Comment by khaes-kth** [comment]
> Could be also implemented as a GH Check?

If it is possible to specify what checks you want to be triggered on your PR, yes, that would be even better. What I had in mind was that not all the PRs should be checked against a specification. They should be checked only if the PR creator asks for it to expedite the review process.

**Comment by monperrus** [comment]
Great!

> should I move this to the Spoon repo?

Yes, let's also post it on Spoon with the label mastersthesis, it will have give it more visibility

**Comment by khaes-kth** [comment]
Added a similar issue on Spoon: https://github.com/INRIA/spoon/issues/4582

**Comment by monperrus** [comment]
closing old stuff
