### ISSUE TITLE
File path is wrong in all_instances_found.json after following readme example

### ISSUE THREAD

**Issue by Gnafu** [SpoonLabs/coming#253]
I'm following the readme and after an install and test I tried the example comand to "Extract all commits of repogit4testv0 that insert a binary operator AST node".

Here's how to reproduce:

```
git clone https://github.com/SpoonLabs/coming.git
cd coming/
mvn install -DskipTests
cd repogit4testv0/
git fetch
git pull
cd ..
java -classpath ./target/coming-0-SNAPSHOT-jar-with-dependencies.jar fr.inria.coming.main.ComingMain -location  ./repogit4testv0/ -mode mineinstance -action INS -entitytype BinaryOperator   -output ./out
```

The `out/all_instances_found.json` file contains a few instances with the following "file" values:

```
"file": "/home/tester/coming/src/CharSequenceUtils.java",
[...]
"file": "/home/tester/coming/src/Quaternion.java",
```

but the files actual paths are :

/home/tester/coming/repogit4testv0/src/CharSequenceUtils.java
/home/tester/coming/repogit4testv0/src/Quaternion.java

the "repogit4testv0" directory is missing from the path

**Comment by monperrus** [comment]
thanks for the report, I can reproduce the bug locally. looking into it.

**Comment by monperrus** [comment]
fixed in https://github.com/SpoonLabs/coming/pull/257
