### ISSUE TITLE
running prophet4j

### ISSUE THREAD

**Issue by mainjar1** [SpoonLabs/coming#261]
I followed the steps to build the project. However, I couldn't make the tool produce prophet4J features for repogit4testv0. Actually, I couldn't find instructions to produce p4j features. Could you please guide me regarding this problem?

**Comment by monperrus** [comment]
hi @mainjar1 

which mode do you use? Prophet4J features are only available in mode `files`

FYI WIP in https://github.com/SpoonLabs/coming/pull/262

**Comment by monperrus** [comment]
potential fix in branch fixfeature. Could you give it a try?

**Comment by monperrus** [comment]
Hi @mainjar1 this is fixed in master, see #263
