### ISSUE TITLE
Diff mode output is empty on "large" files

### ISSUE THREAD

**Issue by gOATiful** [SpoonLabs/coming#264]
Running the command:
`java -classpath ./coming.jar fr.inria.coming.main.ComingMain -input filespair -location Util_before.java:Util_after.java  -mode diff -output out`

Returns without and error, but the fields in the created JSON are empty:
```json
{
  "frequency": [],
  "frequencyParent": [],
  "probability": [],
  "probabilityParent": []
}
```
Which is *not* expected, since there are changes in L147 and L161.

However, removing unchanged lines from both files to a file length of about 700 lines, produces out again:
```json
{
  "frequency": [
    {
      "c": "Class",
      "f": "1"
    }
  ],
  "frequencyParent": [
    {
      "c": "update-node_Class_Package",
      "f": "1"
    }
  ],
  "probability": [
    {
      "c": "Class",
      "f": "1.0"
    }
  ],
  "probabilityParent": [
    {
      "c": "update-node_Class_Package",
      "f": "1.0"
    }
  ]
}
```

This output is also not expected, since the change involves the removal of boolean literals in a function invocation.

Please find the used files attached.
[used_files.zip](https://github.com/SpoonLabs/coming/files/15161301/used_files.zip)

**Comment by monperrus** [comment]
thanks for the bug report.

Fix WIP in progress in #265 

Was partially due to a bug in gumtree-spoon-ast-diff fixed in https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/313
