### ISSUE TITLE
Missing 150 codeDescriptionFeatures?

### ISSUE THREAD

**Issue by YuningLi0902** [SpoonLabs/coming#269]
Hi, authors!
I'm trying to generate the 202 ODS features following the instructions in README, with the command "java -classpath target/coming-0-SNAPSHOT-jar-with-dependencies.jar fr.inria.coming.main.ComingMain -input files -mode features -location pairsD4j -output ./out".

It seems that there are over 10k features the generated json file. I have found the 26 contextualSyntacticFeatures and 26 repairPatternFeatures in this json file, but I cannot find the 150 codeDescriptionFeatures which start with "P4J_SRC/FORMER/LATER". I can only find 10 features named "P4J_ABSTRACT_V_AF",  "P4J_BOP_EQ_AF",  "P4J_BOP_NE_AF", "P4J_GLOBAL_VARIABLE_VF", "P4J_LV_NULL_VF", "P4J_MODIFIED_VF", "P4J_POS_C", "P4J_REPLACE_COND_RF", "P4J_R_STMT_COND_SF", and "P4J_STMT_COND_SF" when I search "P4J" in the json file.

Am I wrong in any step?

**Comment by monperrus** [comment]
Hi @YuningLi0902 

Those features may have been renamed. Do you find something similar in the 10k features you're referring to?

**Comment by monperrus** [comment]
I understand, the code has been removed in #766. I will resuscitate it.

**Comment by monperrus** [comment]
Hi @YuningLi0902 could you try with branch https://github.com/SpoonLabs/coming/tree/clean-extended and let me know how it goes.

**Comment by YuningLi0902** [comment]
It works. Thanks for your support!
Besides I notice that there are 9 features of contextualSyntacticFeatures whose types are string (such as "S13_TYPE_OF_FAULTY_STATEMENT_AFTER_1"). I'm wondering that whether they could be convert into a vector of fixed length via one-hot encoding. Maybe the length is related to actual numbers of enumerations of these features? For example, if there is only one sample to be test for ODS, in the preprocessing procedure of extracting 202 features, since the values of the 9 string-type features are unique respectively, whether the converted vector is shorter than that in training datasets?

**Comment by monperrus** [comment]
great!

> Besides I notice that there are 9 features of contextualSyntacticFeatures whose types are string
could you list them?

What's the problem with having strings?

**Comment by YuningLi0902** [comment]
They are "S13_TYPE_OF_FAULTY_STATEMENT_AFTER_1/2/3", "S13_TYPE_OF_FAULTY_STATEMENT_BEFORE_1/2/3", "S14_TYPE_OF_FAULTY_STATEMENT_PARENT", "S3_TYPE_OF_FAULTY_STATEMENT", and "S11_FAULTY_CLASS_EXCEPTION_TYPE" (according to the TABLE 3 of ODS's paper, "faultyClassExceptionType" is a string-type feature as well, although I found it is a binary value "false" in the generated json file).

There's no problem about the correctness of the extraction I think. I mean, in the pipeline of ODS, these string-type features will be converted into one-hot vectors later, but it seems that the length of the one-hot vector is related to the number of values of specific feature. For example, if "S3_TYPE_OF_FAULTY_STATEMENT" has 2 enumerable values like "while" and "if", it will be converted into a one-hot vector whose length is 2, where [1, 0] represents "S3_TYPE_OF_FAULTY_STATEMENT" equals the value "while" and [0, 1] represents "S3_TYPE_OF_FAULTY_STATEMENT" equals the value "if" (do I understand the ODS pipeline rightly?). I'd like to know whether all the possible values of these string-type features are available, maybe there are 50 different values in total, so that I can set the length of target one-hot vector to 50 to represent what value it equals.

**Comment by monperrus** [comment]
>  I'd like to know whether all the possible values of these string-type features are available

for code element type, yes, there is a fixed number of structures in the programming language.

for class type (S11_FAULTY_CLASS_EXCEPTION_TYPE), this is open ended, it could be any qualified name.

> "faultyClassExceptionType" is a string-type feature as well, although I found it is a binary value "false" in the generated json file

That may be a bug, would you give a try to fix it?

**Comment by YuningLi0902** [comment]
It make me confused that ODS's paper says there are 9 features of the string type meanwhile /docs/ODS.md says that the number is 8.
> Contextual Syntactic Features: Type Features
ODS has 8 features, of type String, that indicates the type (e.g., If, While, assignment) of a particular statement.

Also in /docs/ODS.md, is describes "faultyClassExceptionType" as follows:

> A last boolean feature related to Type is:
· faultyClassExceptionType: indicates whether the associated method or class for the faulty line throws exception.

Should I trust the paper or the .md file?

**Comment by monperrus** [comment]
>  faultyClassExceptionType: indicates whether the associated method or class for the faulty line throws exception.

OK, so faultyClassExceptionType is not a string feature, it is indeed a boolean feature. No need to fix then.

The code is the reference (not the paper, not the markdown documentation).

**Comment by YuningLi0902** [comment]
All right.

> for code element type, yes, there is a fixed number of structures in the programming language.

So what is the final length of the converted feature vectors from the basic 202 ODS features? I think it matters. Maybe the length is 194+8*n, where n is the fixed number of structures in the programming language? I'm curious about the precise n of Java.

**Comment by monperrus** [comment]
> Maybe the length is 194+8*n, where n is the fixed number of structures in the programming language? 

yes.

> I'm curious about the precise n of Java.

me too, would love to see it, please share if you compute it.

**Comment by YuningLi0902** [comment]
OK, I'll try.
Thanks a lot for your patient answers!

**Comment by monperrus** [comment]
FYI, pushed the latest commit to master.

Closing this issue as handled.
