### ISSUE TITLE
Coming can’t be used on a larger git repo

### ISSUE THREAD

**Issue by Thsss** [SpoonLabs/coming#27]
### Description
When I attempted to input a git repository with 2000+ commits, I didn't get the same result as the test data set. Similarly, when input another git repository with 2000+commits, the results were the same.

- Win10+jdk1.8
- input repositories：
1.ctripcorp/apollo (https://github.com/ctripcorp/apollo)
2.mozilla-mobile/focus-android (https://github.com/mozilla-mobile/focus-android)

### Input command
`java -classpath ./target/coming-0.1-SNAPSHOT-jar-with-dependencies.jar fr.inria.coming.main.ComingMain -location  ./*/ -mode mineinstance -pattern ./pattern_INS_IF_MOVE_ASSIG.xml   -output ./out/*`

### CMD output
![image](https://user-images.githubusercontent.com/26516800/54188224-38f30f00-44ea-11e9-8b71-19e577a171c7.png)

**Comment by martinezmatias** [comment]
Dear @Thsss 
Thanks a lot for reporting the bug.
It seems that the problem is when it calculates the diff between two files from a commit.
Cheers
Matias

**Comment by martinezmatias** [comment]
Dear @Thsss 
I pushed a patch for that problem. I think that the issue is not related to large repos, but it's related to a failure in the diff which has more probability to appear in large repos.
WDTY?
Regards
Matias

**Comment by Thsss** [comment]
Wow, I think it's fixed. 
Thanks!❤
