### ISSUE TITLE
Using File.pathSeparator as substitution for colon will cause problem on Windows system

### ISSUE THREAD

**Issue by rem2016** [SpoonLabs/coming#28]
As you can see from [here](https://stackoverflow.com/questions/5971964/file-separator-or-file-pathseparator), on Win File.pathSeparator is `;` rather than `:` which causes four failures when I ran testing on my Win machine. 

In those errors, `File.pathSeparator` simply serves as the character `:` rather than *pathSeparator* that diffs on different systems. For example, README says you need the following command to combine filters,

     -filter numberhunks:maxfiles  -parameters max_nb_hunks2:max_files_per_commit:1

where `:` is used to separate different parameters and filter.

I will make a PR soon to fix problems like this.

**Comment by martinezmatias** [comment]
Dear @rem2016 
Thanks a lot the the issue and the PR.
You are right, on Windows the pathSeparator is a ';'.
The change you propose is correct.
Thanks!
Cheers
Matias
