### ISSUE TITLE
How to write the pattern specification to match the change of IF ccondition

### ISSUE THREAD

**Issue by rem2016** [SpoonLabs/coming#36]
I want to match the change of IF condition, i.e.

```
- if (a){
+ if (b){
    System.out.println(a);
}
```

I have tried the specification like this one below:

```xml
<?xml version="1.0"?>
<pattern>
<entity id="1" type = "If"/>
<entity id="2" type = "*">
	<parent parentId="1" distance="10" />
</entity>
<action entityId ="2" type = "*" />
</pattern>
```
But it will also capture the change in the if block. For example, it will also match the change like this one.

```
if (a){
-    System.out.println(a);
+    System.out.println(a);
}
```

How should I write the Pattern Specification to **only** match the changes in the condition part?

**Comment by martinezmatias** [comment]
Hi @rem2016 
It's a good point.
The pattern you wrote is to detect any change inside one AST which root is the IF.
As you mention, both changes (one inside the condition and the other inside a statement) correctly match with the pattern. What is missing in our pattern specification is to say that you want to match the change that is inside the condition of the If. There, the problem is  that in the AST there is not a AST node which type is "If condition". (We have the node (a) but there is not info about its role in the parent.). 
To overcome that I have one idea that could improve the pattern specification.
Let me try to implement and to see if it works.
Thanks!!
Regards
Matias

**Comment by rem2016** [comment]
Thanks for your quick response!

I partially solve this problem by modifying the code to supporting a special action type call "Unchanged," which means that the corresponding entity does not change. To solve the only-in-if-condition problem, I use the following specification:

```xml
<?xml version="1.0"?>
<pattern>
    <entity id="1" type="If" />
    <entity id="2" type="*">
        <parent parentId="1" distance="10000"/>
    </entity>
    <entity id="3" type="Block">
        <parent parentId="1" distance="1"/>
    </entity>
    <entity id="4" type="*">
        <parent parentId="3" distance="10000"/>
    </entity>
    <action entityId="4" type="UNCHANGED"/>
    <action entityId="2" type="*" />
</pattern>
```

**Comment by martinezmatias** [comment]
Hi @rem2016 
That's a very good feature.

FYI: the initial version of the pattern specification presented in our paper ICSME13 has the option to specify the entities that are affected and those that are not affected. In this new implementation of Coming (prepared last year), I left this feature for future work.

Could you prepare a Pull request with the feature? (with a test case that tests it).

Thanks a lot!
Martias

**Comment by rem2016** [comment]
NP! 😄 

Not sure whether my implementation has some side-effects, I need to write a few more tests. I'll make a PR asap.

**Comment by martinezmatias** [comment]
perfect! thanks a lot!

**Comment by rem2016** [comment]
I'm a little confused about the naming convention in the pattern tests' resources. In /src/main/resources/casesDj4 there are some folders named `math_n` where n is a number, and the number seems quite random. If I want to create my test case, which `n` should it be?

**Comment by martinezmatias** [comment]
The folder casesDj4 are examples of patches (i.e., buggy and patched pair of files) taken from Defects4J. The n corresponds to one Ids assigned by the Defects4J authors.

I would suggest to create your test examples into `/coming/src/main/resources/patterns_examples`

(I have to clean that resource folder, sorry for that)

**Comment by rem2016** [comment]
Got it. Thanks.

**Comment by rem2016** [comment]
When I was merging the latest changes that fixed [the different entities issue](https://github.com/SpoonLabs/coming/issues/38), I found the workaround I mentioned above cannot work well, i.e.

```xml
<?xml version="1.0"?>
<pattern>
    <entity id="1" type="If" />
    <entity id="2" type="*">
        <parent parentId="1" distance="10000"/>
    </entity>
    <entity id="3" type="Block">
        <parent parentId="1" distance="1"/>
    </entity>
    <entity id="4" type="*">
        <parent parentId="3" distance="10000"/>
    </entity>
    <action entityId="4" type="UNCHANGED"/>
    <action entityId="2" type="*" />
</pattern>
```

The problem is when an operation match both UNCHANGED entity and another entity, should it be a mismatch because UNCHANGED has a higher priority, or should it be a match with another entity because UNCHANGED has a lower priority?

In the above example, it should be a mismatch, because I don't want anything changed inside the Block. In some cases, I may also want it to be a match. Examples include adding the parameter:

```java
- call(a,b);
+ call(a,b,c);
``` 

We can use the following specification to match it if UNCHANGED has a lower priority.

```xml
<?xml version="1.0"?>
<pattern>
    <entity id="1" type="Invocation"/>
    <entity id="2" type="*">
        <parent parentId="1" distance="10000"/>
    </entity>
    <entity id="3" type="*">
        <parent parentId="1" distance="1"/>
    </entity>
    <action entityId="2" type="UNCHANGED"/>
    <action entityId="3" type="INS"/>
</pattern>
```

I think the other action types do not have this priority problem. Different priority settings can only lead to different ways of matches and won't affect the results. However UNCHANGED action is different, and it will lead to totally different results.

# Possible Solutions

1. For UNCHANGED action, let the action tag including another field to indicate the priority or which entities it can be compatible with.
2. Use two ActionType, one with high priority and one with lower.
