### ISSUE TITLE
DetectorChangePatternInstanceEngine does not distinguish different entities

### ISSUE THREAD

**Issue by rem2016** [SpoonLabs/coming#38]
In the current implementation, I notice that the following pattern specification will also match the change with only one TypeReference entity insert.

```xml
<?xml version="1.0"?>
<pattern>
    <entity id="1" type="TypeReference"/>
    <entity id="2" type="TypeReference"/>
    <action entityId="1" type="INS"/>
    <action entityId="2" type="INS"/>
</pattern>
``` 

This specification would match

```java
+ int c;
```

In other words, the entities with different ids may match the same operation in the AST.

Is this by design? I would prefer that the engine distinguishes entities with different IDs, which is more flexible.

I think the implementation may be [here](https://github.com/SpoonLabs/coming/blob/de0906fa548e80674bc2fea682b0b07cea25d276/src/main/java/fr/inria/coming/changeminer/analyzer/instancedetector/DetectorChangePatternInstanceEngine.java#L73).

**Comment by martinezmatias** [comment]
Thanks @rem2016  for reporting the problem.
I am working on the solution.
Regards
Matias

**Comment by martinezmatias** [comment]
Dear @rem2016 

I have pushed a patch for fixing the problem you reported.

You can fin the test case [](https://github.com/SpoonLabs/coming/commit/5ec1534a3f36bd7a9d534e0dd4380af867466d9b#diff-d1fc580f6be7b98279dadf443320192c)

Thanks for helping us to improve the tool!

Regards
Matias

**Comment by rem2016** [comment]
Amazing! Thanks!

**Comment by martinezmatias** [comment]
Dear @rem2016 
I will push the updated documentation in few minutes.
Regards
Matias

**Comment by martinezmatias** [comment]
HI @rem2016 
Here you can find the documentation about the use of role: https://github.com/SpoonLabs/coming/blob/master/README.md#roles-of-entities

Please, if you have any comment/change/improvement, don't hesitate to write us.

Regards
Matias
