### ISSUE TITLE
New input

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/coming#58]
New kind of input: to have two arguments corresponding to two files. Then, coming executes the analyzers over the pair.

**Comment by sedflix** [comment]
Doesn't `-input files` do kind of the same thing? 
Though, it needs to be encapsulated within three folders with a particular folder hierarchy. 
 
What args are `-input` and `-location` supposed to have in the given case?

**Comment by martinezmatias** [comment]
Hi @sedflix 

> Doesn't -input files do kind of the same thing?

This new input will target to have two arguments e.g., - file_left and -file_right. 
The goal will be to analyze only one pair  of files, given by the previous two arguments.

> What args are -input and -location supposed to have in the given case?

In fact, maybe we should rename 'input' by 'inputtype' (I will do it after the conference).
So I imagine that for this new input location will not be required.
WDYT?

**Comment by sedflix** [comment]
> In fact, maybe we should rename 'input' by 'inputtype' (I will do it after the conference).

Yeah. I think that same I made an issue for the same #64 earlier. 

> So I imagine that for this new input location will not be required.
> WDYT?

One of the choices could be to use `-location` in the form of `<file_left>:<file_right>` instead of introducing a new option. Adding two new arguments is more expressive but it also increases the number of options.

**Comment by martinezmatias** [comment]
> the choices could be to use -location in the form of <file_left>:<file_right>

It's a good idea. Let's go for that option. (As separator we use File.pathSeparator)

**Comment by sedflix** [comment]
Cool!
What would be the name of this input?

**Comment by martinezmatias** [comment]
> What would be the name of this input?

Let's say "filepair", something like that

**Comment by monperrus** [comment]
Done in "filespair" format
