### ISSUE TITLE
UNCHANGED action

### ISSUE THREAD

**Issue by sedflix** [SpoonLabs/coming#85]
*Concerned patch:*
```diff
--- /src/com/google/javascript/rhino/testing/Asserts.java
+++ /src/com/google/javascript/rhino/testing/Asserts.java
@@ -102,3 +102,3 @@
         (a == null) == (b == null));
-    if (a == null) {
+    if (message!=null) {
       return;
```

The pattern is not supposed to match the given change because `a` has been changed to `message`.

*Pattern Specification:*
```
<pattern name="binary">

    <entity id="1" type="BinaryOperator"/>

    <entity id="2" type="*" role="LEFT_OPERAND"> 
        <parent parentId="1" distance="1"/>
    </entity>

    <entity id="3" type="*" role="RIGHT_OPERAND"> 
        <parent parentId="1" distance="1"/>
    </entity>

    <action entityId="1" type="UPD"/>
    <action entityId="2" type="UNCHANGED_HIGH_PRIORITY"/>
    <action entityId="3" type="UNCHANGED_HIGH_PRIORITY"/>
</pattern>

```

*Instance matched:*
```
 "instance_detail": [                                                                                                                                                                   
            {                                                                                                                                                                                    
              "pattern_action": "UPD",                                                                                                                                                           
              "pattern_entity": {                                                                                                                                                                
                "entity_type": "BinaryOperator",                                                                                                                                                 
                "entity_new value": "*",                                                                                                                                                         
                "entity_role": "*",                                                                                                                                                              
                "entity_parent": "null"                                                                                                                                                          
              },                                                                                                                                                                                 
              "concrete_change": {                                                                                                                                                               
                "operator": "UPD",                                                                                                                                                               
                "src_type": "BinaryOperator",                                                                                                                                                    
                "dst_type": "BinaryOperator",                                                                                                                                                    
                "src": "a == null",                                                                                                                                                              
                "dst": "message != null",                                                                                                                                                        
                "src_parent_type": "If",                                                                                                                                                         
                "dst_parent_type": "If",                                                                                                                                                         
                "src_parent": "if (a == null) {\n    return;\n}",
                "dst_parent": "if (message != null) {\n    return;\n}"
              },
              "file": "/home/ubuntu/coming/patch1-Closure-7-Nopol2017",
              "line": 103
            }
          ]

```

The concerned files can be found [here](https://github.com/kth-tcs/defects4j-repair-reloaded/tree/comrepair-coming/coming_data/Nopol/patch1-Closure-7-Nopol2017/patch1-Closure-7-Nopol2017) (private repo)

**Comment by sedflix** [comment]
Hi @martinezmatias 
This is probably happening because we are using the old version of gumtree-spoon-ast-diff. The current version should fix this.

Old version just detects one change while the current one detects two.

**Comment by martinezmatias** [comment]
Hi @sedflix 
> This is probably happening because we are using the old version of gumtree-spoon-ast-diff. The current version should fix this.

I dont think that is a problem of GT-Spoon version. The current version of GT-Sp used by Coming is the 1.20, which is the last one. (I update it last week)

> Can you please update the version?

We are using the last version since last week.

> And is the libs directory required now?

I did not get this point.

Cheers
Matias

**Comment by sedflix** [comment]
> I dont think that is a problem of GT-Spoon version. The current version of GT-Sp used by Coming is the 1.20, which is the last one. (I update it last week)

Oh yeah! Sorry. The fork on my system was out of date. 
Since the GT-Spoon gives two diff points(variable read and binary operator), the problem is not in the diff tree as mentioned by you in the mail. 

> I did not get this point.

There is a folder in this repo called `lib`? Is it being used anywhere?

**Comment by martinezmatias** [comment]
Hi @sedflix 

> There is a folder in this repo called lib? Is it being used anywhere?

I have just removed it. It was not used any more. Thanks for pointing me that issue.

Cheers
Matias

**Comment by sedflix** [comment]
Well, this is kind of funny.

I was not able to find any kind of bug in `DetectorChangePatternInstanceEngine` and by chance, I looked at the values of `roleInParent` during Role comparison and hence found that the error is due to the role: "RIGHT_OPERAND". It's not supposed to be separated by `_`.

**Comment by sedflix** [comment]
I somehow missed this during the test and was trying to make for the past days 

The pattern `binary` doesn't match the patch discussed [above](https://github.com/SpoonLabs/coming/issues/85#issue-457498598).  But it doesn't match the following changes:

```diff
patch4-Closure-21-jMutRepair
121c121
<           if (ancestorType != Token.EXPR_RESULT && ancestorType != Token.BLOCK) return;
---
>           if (ancestorType != Token.EXPR_RESULT && ancestorType >= Token.BLOCK) return;
patch3-Time-11-jMutRepair
1144c1144
<                 if (startRule.getToYear() == Integer.MAX_VALUE &&
---
>                 if (startRule.getToYear() > Integer.MAX_VALUE &&
patch3-Math-81-jMutRepair
1537c1537
<                 if (work[np - 8] > b2 || work[np - 4] > b1) {
---
>                 if (work[np - 8] < b2 || work[np - 4] > b1) {
patch5-Closure-21-jMutRepair
121c121
<           if (ancestorType != Token.EXPR_RESULT && ancestorType != Token.BLOCK) return;
---
>           if (ancestorType != Token.EXPR_RESULT && ancestorType > Token.BLOCK) return;
patch1-Math-104-jMutRepair
162c162
<         } else if (a >= 1.0 && x > a) {
---
>         } else if (a >= 1.0 && x >= a) {

```


**The concerned pattern**:
```
<pattern name="binary">

    <entity id="1" type="BinaryOperator"/>
    <action entityId="1" type="UPD"/>

    <!-- For making sure that operands remains the same -->
    <entity id="2" type="*" role="LeftOperand">
        <parent parentId="1" distance="1"/>
    </entity>
    <action entityId="2" type="UNCHANGED_HIGH_PRIORITY"/>

    <entity id="3" type="*" role="RightOperand">
        <parent parentId="1" distance="1"/>
    </entity>
    <action entityId="3" type="UNCHANGED_HIGH_PRIORITY"/>

</pattern>
```

**Comment by martinezmatias** [comment]
Hi @sedflix 
> But it doesn't match the following changes:
I would suggest to create one test case for each case. (At least for some of them).
Then, we can print the AST output to be sure that the diff that coming consumes is correct, and eventually to refine the pattern to detect such changes.

**Comment by sedflix** [comment]
Will create test cases.

**Comment by sedflix** [comment]
**Case 1**
```diff
+ work[np - 8] < b2
- work[np - 8] > b2
````

In this case, only the following pattern will work [binary_2.xml](https://github.com/sedflix/coming/blob/bbc0ab321a0f3038fff7714ea6e2f85ba6552a07/src/main/resources/repairability/JMutRepair/binary_2.xml)

**Case 2**
```diff
+ b2 < work[np - 8]
-  b2 > work[np - 8]
````

In this case, only the following pattern will work [binary_3.xml](https://github.com/sedflix/coming/blob/bbc0ab321a0f3038fff7714ea6e2f85ba6552a07/src/main/resources/repairability/JMutRepair/binary_3.xml)

**Case 3**
```diff
+ b2 < b1
-  b2 > b1
````

In this case, only the following pattern will work [binary_1.xml](https://github.com/sedflix/coming/blob/bbc0ab321a0f3038fff7714ea6e2f85ba6552a07/src/main/resources/repairability/JMutRepair/binary_1.xml)

**Case 4**
```diff
+  work[np - 8] <  work[np - 4]
-  work[np - 8] >  work[np - 4]
````

In this case, only the following pattern will work [binary_4.xml](https://github.com/sedflix/coming/blob/bbc0ab321a0f3038fff7714ea6e2f85ba6552a07/src/main/resources/repairability/JMutRepair/binary_4.xml)


Case 2 produces false positives by matching the diff below to case 1. `a` and `message` are not compared and since they have no child elements they are considered changed in case 1 pattern. 
Similarly, false negatives are created in case 2,3,4.
```diff
+ a == null
- message != null
```
