### ISSUE TITLE
Patterns with multiples instances

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/coming#94]

**Comment by martinezmatias** [comment]
Discussion started in PR: https://github.com/SpoonLabs/coming/pull/93#issuecomment-505442662
We move the conversation here.

**Comment by martinezmatias** [comment]
From https://github.com/SpoonLabs/coming/pull/93#issuecomment-505442662

**Comment by martinezmatias** [comment]
> Maybe this issue is related to the fact that the matcher is considering all the operations rather than the root (see here )
> WDYT?
> What do you think about considering only roots actions rather than all actions in the instance matching process? (not only related to this case)
> 
> I like this option. I trying to make this work(as it would require a few changes in the pattern files).
> We will put a condition like "if the mode is repairability consider only root instances", right?

Not sure if we have to consider only on `repairability` mode, or everywhere.  I would say that every matching is done by considering only roots. We can put as an option, where the default value is "matching root"

**Comment by sedflix** [comment]
If the default value is "matching root", it would result is many(~40) failing test cases?

**Comment by martinezmatias** [comment]
> If the default value is "matching root", it would result is many(~40) failing test cases?

:/ I though that the change will not impact in that way

**Comment by martinezmatias** [comment]
I am thinking the potential solutions, for the moment I dont have any preference.
To consider `all` actions were easier to describe some patterns
example Add- If return
There we specified two entities, one pattern relation, and two actions
With the `root` change, the matcher will not return an instance for that pattern because the change related to the `return` is not included in the root action list.

**Comment by martinezmatias** [comment]
Maybe the easier solution is to post-process the instances.

**Comment by sedflix** [comment]
Sounds good to me!
