### ISSUE TITLE
Designing test cases for repairability

### ISSUE THREAD

**Issue by sedflix** [SpoonLabs/coming#97]
Hi @martinezmatias ,

I have a doubt about designing test cases. I think I've two options right now:

- Use @BeforeAll to process all the input files at once. After that, we just need to analyze the results in each of the test cases. Hence, the heavy processing is done only once.

- The other is the usual choice of dividing files into different sets of test cases. This may result in a repetition of the same file as well as the processing of the same file more than once.

It's a tradeoff between testing time and modularity of test cases.

WDYT?

**Comment by martinezmatias** [comment]
Hi @sedflix 
I would say the second one for one reason: In case of debugging on particular test case that option computes only the diffs involved in that case.
WDYT?
Regards
Matias

**Comment by sedflix** [comment]
Yeah. That's a good point too. I will continue with the second approach. 

Maybe at some later stage, we should work on the resources taken by coming to make it faster and lighter.
