### ISSUE TITLE
Repairability: JGenProg

### ISSUE THREAD

**Issue by sedflix** [SpoonLabs/coming#98]
Hi @martinezmatias and @monperrus ,
This issue is regarding the question of how should we handle the patches for JGenProg. 

Here most of the patches are:
1) Insert a new block/statement
2) Delete a new block/statement
3) Insert some statement/block as well as delete the statement/block

These are very weak conditions by itself and all the commits lie in one of these categories. 

And since the paper applies diff minimization, from my perspective, it would be hard(with only the current features of coming) to figure out whether the new statement inserted already existed in the code or not. 

Q1. ) Does our implementation(the patches in DRR) use diff minimization?

Q2. ) Do we want to include other characteristics into coming?  For example, running test cases and seeing the paths followed in the buggy version or other analysis based on test cases results. Or maybe accepting only git repo as an input for certain kind of repair-tool analysis so that we can search through code(like jGenProg). Or about including diff minimization dependencies?

Q3. ) How strong indicator our classification is supposed to be of that patch being generation by the concerned repair tool?

#66

**Comment by martinezmatias** [comment]
Hi @sedflix 

> These are very weak conditions by itself and all the commits lie in one of these categories

I don't agree. For Insert/Replace, the code must be already present into the application (for simplification, I would be much easier if we consider only in the class under modification).  Otherwise, if the inserted code is not present, there is not an instance of a patch of Genprog in the commit.

> And since the paper applies diff minimization, from my perspective, it would be hard(with only the current features of coming) to figure out whether the new statement inserted already existed in the code or not.

I am not sure whether diff minimization is important in our detector. I would say that we simply have to check if every inserted statement (or code element at other granularity) from the patch exists in the previous version (i.e., the *left* part of the diff).  

Do you have an example that shows that minimization has an impact into our processor?

> Q1. ) Does our implementation(the patches in DRR) use diff minimization?

I would say No.

> Q2. ) Do we want to include other characteristics into coming? For example, running test cases and seeing the paths followed in the buggy version or other analysis based on test cases results. 

I would say No. Which would those new characteristics be used for? 
 

> Q3. ) How strong indicator our classification is supposed to be of that patch being generation by the concerned repair tool?

I dont get the point. Could you clarify it?

Thanks
Regards
Matias

**Comment by sedflix** [comment]
I'm so sorry for this premature issue. I just had completed reading the paper and analyzed a very few JGenProg patches, in all of which inserted statement was not present in the class. 


 > For Insert/Replace, the code must be already present into the application...

On further analysis yes most of the addition commit belong to this category.

> Do you have an example that shows that minimization has an impact into our processor?

Not at this moment. I came to the conclusion behind the minimization thing by just reading the paper. 

> Which would those new characteristics be used for?

I think that these characteristics will make our classification stronger as we could only label revisions that have some localization probability(for example use number of time that lines was executed in failing test cases or passing ones) or apply stronger checks maybe. Also, I think that this is an extreme case and I was just wondering you had any future plans about this.

**Comment by martinezmatias** [comment]
Hi @sedflix 

> that have some localization probability(for example use number of time that lines was executed in failing test cases or passing ones) or apply stronger checks maybe. It might help in filtering only delete patches. Also, I think that this is an extreme case and I was just wondering you had any future plans about this.

It's a very good idea to complement the static analysis we do in Coming with dynamic analyses. For example, the information you ask can be taken from Astor (https://github.com/SpoonLabs/astor). 
However, take into account that for doing dynamic analysis (or in particular running Astor) you will need to a) checkout the complete version associated to one commit, and b) build that version. Doing that for each commit would be very expensive. (But I could be applied over a filtered set of commits, after the static analysis)

**Comment by sedflix** [comment]
Yeah, it's gonna be really expensive in terms of computational. We could add the thing about including dynamic analysis to coming at a future feature and make an issue out of it.

**Comment by sedflix** [comment]
Hi @martinezmatias ,

Right now, I'm trying to find the inserted statement or the moved statement in the previous version of the file. 

String comparison doesn't work as the statement in the next verision of the file can have different formatting like:  `((isNaN) || (rhs.isNaN))` v/s `(isNaN || rhs.isNaN)`.

I'm thinking about using `AstComparator().compare((CtElement) elementWithRoleStatement, (CtElement) ctClassPreviousVersion);` and searching for any `MOV` operations in the result. If a move operation is present, then the statement was present in the previous version otherwise not. 

But I have a feeling that Spoon's Pattern or Matcher feature will be a better option for doing the same but I'm unable to figure out how to implement those.

Is using AstComparator fine? If not, can you please help me a bit in implementing that pattern matching?

In reference with PR #99

**Comment by sedflix** [comment]
> I'm thinking about using AstComparator().compare((CtElement) elementWithRoleStatement, (CtElement) ctClassPreviousVersion); and searching for any MOV operations in the result. If a move operation is present, then the statement was present in the previous version otherwise not.

This won't work too.

**Comment by sedflix** [comment]
> Can you please help me a bit in implementing that pattern matching?

Apparently, there seems to be a bug in Spoon PatternBuilder.

**Comment by sedflix** [comment]
> ... code must be already present into the application (for simplification, I would be much easier if we consider only in the class under modification). 

There are around 23 patches out of 153 patches in DRR repo that have insertion statements that don't belong to the previous version of the file.
